FROM node:18-alpine

# Accept service name as build argument
ARG SERVICE_NAME

# Install OpenSSL for Prisma, Bash shell
RUN apk add --no-cache openssl bash

WORKDIR /app

# Copy base files
COPY package*.json ./
COPY tsconfig.base.json ./
COPY common ./common

# Copy only the requested service folder
COPY services/${SERVICE_NAME} ./services/${SERVICE_NAME}

# Install all dependencies including dev for TS build
RUN npm install

COPY common/package.json ./common/
COPY common/tsconfig.json ./common/
COPY services/${SERVICE_NAME}/package.json ./services/${SERVICE_NAME}/
COPY services/${SERVICE_NAME}/tsconfig.json ./services/${SERVICE_NAME}/

# install per-service dependencies
RUN npm install --workspace=common
RUN npm install --workspace=services/${SERVICE_NAME}

# create folders so volumes can mount cleanly
RUN mkdir -p common/dist services/${SERVICE_NAME}/dist

WORKDIR /app/scripts
# Copy the 'wait-for-it' script
COPY scripts/wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it
# Copy the 'wait-for-services' script
COPY scripts/wait-for-services.sh ./
RUN chmod +x /app/scripts/wait-for-services.sh
# Copy the 'common service entrypoint' script
COPY scripts/service-entrypoint.sh ./
RUN chmod +x /app/scripts/service-entrypoint.sh

# Copy the endpoint script
COPY scripts/service-entrypoint.sh /app/services/${SERVICE_NAME}/entrypoint.sh

# Generate wrapper entrypoint
RUN echo '#!/bin/sh' > /app/entrypoint.sh && \
    echo 'set -euo pipefail' >> /app/entrypoint.sh && \
    echo "exec sh /app/services/${SERVICE_NAME}/entrypoint.sh \"\$@\"" >> /app/entrypoint.sh && \
    chmod +x /app/entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["/app/entrypoint.sh"]
